# Firebase Configuration
firebase.credential.path=classpath:firebase/serviceAccountKey.json
# Uncomment the line below if you prefer using an absolute path on your system instead of placing the file in src/main/resources
# firebase.credential.path=file:///C:/full/path/to/serviceAccountKey.json

# Server port Configuration
server.port=8080